### ISSUE TITLE
Question about Confident Learning

### ISSUE THREAD

**Issue by icecity96** [microsoft/UST#1]
According to your paper, sample weight should be `Var(y)`

In `sampleer.py` line 76:
```python
for label in range(num_classes):
      # .....
       w_s.extend(y_var_[indices][:,0])
```
Why there always take class0's confidence?

Does this line should be:
```python
w_s.extend(y_var_[indices][:, label]
```

**Comment by MarcusT1K24** [comment]
I have set up the environment as requirement.txt, follow all steps in README but this error keeps happening, please help me

Traceback (most recent call last): 

File "UST/run_ust.py", line 147, in <module>

    train_model(max_seq_length, X_train, y_train, X_test, y_test, X_unlabeled, model_dir, tokenizer, sup_batch_size=sup_batch_size, unsup_batch_size=unsup_batch_size, unsup_size=unsup_size, sample_size=sample_size, TFModel=TFModel, Config=Config, pt_teacher_checkpoint=pt_teacher_checkpoint, sample_scheme=sample_scheme, T=T, alpha=alpha, valid_split=valid_split, sup_epochs=sup_epochs, unsup_epochs=unsup_epochs, N_base=N_base, dense_dropout=dense_dropout, attention_probs_dropout_prob=attention_probs_dropout_prob, hidden_dropout_prob=hidden_dropout_prob)`

File "/content/UST/ust.py", line 180, in train_model

    y_mean, y_var, y_pred, y_T = mc_dropout_evaluate(model, gpus, len(labels), X_unlabeled_sample, T=T)

  File "/content/UST/ust.py", line 61, in mc_dropout_evaluate

    y_pred.extend(pred.values[gpu])

AttributeError: 'numpy.ndarray' object has no attribute 'values'

**Comment by lvwerra** [comment]
I am experiencing the same issue. Could it be connected to running the code on a single GPU? Replacing `pred.values[gpu]` with `pred` seems to work.

**Comment by MarcusT1K24** [comment]
Thank you for your help.

Vào CN, 7 thg 3, 2021 vào lúc 20:24 Leandro von Werra <
notifications@github.com> đã viết:

**Comment by Struggle-Forever** [comment]
> According to your paper, sample weight should be `Var(y)`
> 
> In `sampleer.py` line 76:
> 
> ```python
> for label in range(num_classes):
>       # .....
>        w_s.extend(y_var_[indices][:,0])
> ```
> 
> Why there always take class0's confidence?
> 
> Does this line should be:
> 
> ```python
> w_s.extend(y_var_[indices][:, label]
> ```

The same problem occurs with other sampling functions., for example 


```
def sample_by_bald_easiness(tokenizer, X, y_mean, y_var, y, num_samples, num_classes, y_T):
...
	w_s = y_var[indices][:,0]
	return X_s, y_s, w_s
```

I also don't understand here, why the variance of category 0 is always used?

**Comment by Struggle-Forever** [comment]
> > According to your paper, sample weight should be `Var(y)`
> > In `sampleer.py` line 76:
> > ```python
> > for label in range(num_classes):
> >       # .....
> >        w_s.extend(y_var_[indices][:,0])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Why there always take class0's confidence?
> > Does this line should be:
> > ```python
> > w_s.extend(y_var_[indices][:, label]
> > ```
> 
> The same problem occurs with other sampling functions., for example
> 
> ```
> def sample_by_bald_easiness(tokenizer, X, y_mean, y_var, y, num_samples, num_classes, y_T):
> ...
> 	w_s = y_var[indices][:,0]
> 	return X_s, y_s, w_s
> ```
> 
> I also don't understand here, why the variance of category 0 is always used?


Another thing that confuses me is that the variance in the paper uses `log(1/ var(y))`,   However, in the code it is directly calculated using    ` y_var = np.var(y_T, axis=0).`
